-- ============================================================
-- ALLYOUNEEDISANIDEA — Initial Schema
-- Run this in Supabase SQL editor or via supabase db push
-- ============================================================

-- Sites: one row per customer website
create table if not exists public.sites (
  id          uuid primary key default gen_random_uuid(),
  owner_id    uuid references auth.users(id) on delete cascade,
  name        text not null,
  domain      text not null,                    -- e.g. "myapp.com" — enforced on server
  agent_name  text not null default 'Assistant',
  agent_color text not null default '#6366f1',  -- hex, used by embed widget
  system_prompt text not null default 'You are a helpful assistant embedded in this website. You can control the page on behalf of the user. Always confirm before taking destructive actions like cancelling subscriptions or deleting data.',
  allowed_domains text[] not null default array[]::text[],  -- additional allowed domains beyond "domain"
  created_at  timestamptz not null default now()
);

-- Conversations: one per user session
create table if not exists public.conversations (
  id               uuid primary key default gen_random_uuid(),
  site_id          uuid not null references public.sites(id) on delete cascade,
  user_fingerprint text not null,   -- anonymous identifier generated by embed script
  started_at       timestamptz not null default now(),
  last_active_at   timestamptz not null default now()
);

-- Messages: full conversation history
create table if not exists public.messages (
  id               uuid primary key default gen_random_uuid(),
  conversation_id  uuid not null references public.conversations(id) on delete cascade,
  role             text not null check (role in ('user', 'assistant', 'tool')),
  content          text,
  tool_calls       jsonb,       -- array of tool calls when role=assistant
  tool_call_id     text,        -- which tool call this result belongs to when role=tool
  tool_name        text,        -- tool name when role=tool
  created_at       timestamptz not null default now()
);

-- User memories: key-value facts the agent learns per user per site
create table if not exists public.user_memories (
  id               uuid primary key default gen_random_uuid(),
  site_id          uuid not null references public.sites(id) on delete cascade,
  user_fingerprint text not null,
  key              text not null,
  value            text not null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (site_id, user_fingerprint, key)
);

-- Site knowledge: manually added FAQs / docs (pgvector in phase 2)
create table if not exists public.site_knowledge (
  id         uuid primary key default gen_random_uuid(),
  site_id    uuid not null references public.sites(id) on delete cascade,
  title      text not null,
  content    text not null,
  created_at timestamptz not null default now()
);

-- Action logs: audit trail of every DOM action taken
create table if not exists public.action_logs (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.conversations(id) on delete cascade,
  site_id         uuid not null references public.sites(id) on delete cascade,
  action_type     text not null,   -- navigate, click, fill, scroll, etc.
  action_data     jsonb not null,
  result          jsonb,
  confirmed_by_user boolean not null default false,
  created_at      timestamptz not null default now()
);

-- ============================================================
-- Indexes
-- ============================================================
create index if not exists idx_conversations_site_id        on public.conversations(site_id);
create index if not exists idx_conversations_fingerprint    on public.conversations(user_fingerprint);
create index if not exists idx_messages_conversation_id     on public.messages(conversation_id);
create index if not exists idx_user_memories_site_fp        on public.user_memories(site_id, user_fingerprint);
create index if not exists idx_site_knowledge_site_id       on public.site_knowledge(site_id);
create index if not exists idx_action_logs_conversation_id  on public.action_logs(conversation_id);

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.sites          enable row level security;
alter table public.conversations  enable row level security;
alter table public.messages       enable row level security;
alter table public.user_memories  enable row level security;
alter table public.site_knowledge enable row level security;
alter table public.action_logs    enable row level security;

-- Sites: owners can only see their own
create policy "owners manage their sites"
  on public.sites for all
  using (owner_id = auth.uid());

-- Service role bypasses RLS (used by agent server with service key)
-- All other tables are accessed by the agent server via service role,
-- so we allow service role full access and lock down anon/authenticated.

create policy "service role full access on conversations"
  on public.conversations for all
  using (true)
  with check (true);

create policy "service role full access on messages"
  on public.messages for all
  using (true)
  with check (true);

create policy "service role full access on user_memories"
  on public.user_memories for all
  using (true)
  with check (true);

create policy "service role full access on site_knowledge"
  on public.site_knowledge for all
  using (true)
  with check (true);

create policy "service role full access on action_logs"
  on public.action_logs for all
  using (true)
  with check (true);

-- Dashboard: owners can read their own site's knowledge
create policy "owners manage site knowledge"
  on public.site_knowledge for all
  using (site_id in (select id from public.sites where owner_id = auth.uid()));
